2021-11-30T17:46:16.193Z - error: uncaughtException: Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at Query.onResult (D:\2609 PROJECT\app.js:95:20)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:31:14)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10) error=TypeError: Cannot read properties of undefined (reading 'length'), stack=TypeError: Cannot read properties of undefined (reading 'length')
    at Query.onResult (D:\2609 PROJECT\app.js:95:20)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:31:14)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10), exception=true, date=Wed Dec 01 2021 01:46:16 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
2021-11-30T17:47:29.814Z - error: uncaughtException: response is not defined
ReferenceError: response is not defined
    at Query.onResult (D:\2609 PROJECT\app.js:102:8)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11) error=ReferenceError: response is not defined, stack=ReferenceError: response is not defined
    at Query.onResult (D:\2609 PROJECT\app.js:102:8)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11), exception=true, date=Wed Dec 01 2021 01:47:29 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object]
2021-11-30T17:47:53.791Z - error: uncaughtException: response is not defined
ReferenceError: response is not defined
    at Query.onResult (D:\2609 PROJECT\app.js:102:8)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11) error=ReferenceError: response is not defined, stack=ReferenceError: response is not defined
    at Query.onResult (D:\2609 PROJECT\app.js:102:8)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11), exception=true, date=Wed Dec 01 2021 01:47:53 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object]
2021-12-01T18:29:56.944Z - error: uncaughtException: ___dirname is not defined
ReferenceError: ___dirname is not defined
    at Query.onResult (D:\2609 PROJECT\routes\products.js:21:24)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11) error=ReferenceError: ___dirname is not defined, stack=ReferenceError: ___dirname is not defined
    at Query.onResult (D:\2609 PROJECT\routes\products.js:21:24)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11), exception=true, date=Thu Dec 02 2021 02:29:56 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object]
2021-12-01T18:30:05.607Z - error: uncaughtException: ___dirname is not defined
ReferenceError: ___dirname is not defined
    at Query.onResult (D:\2609 PROJECT\routes\products.js:21:24)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11) error=ReferenceError: ___dirname is not defined, stack=ReferenceError: ___dirname is not defined
    at Query.onResult (D:\2609 PROJECT\routes\products.js:21:24)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11), exception=true, date=Thu Dec 02 2021 02:30:05 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object]
2021-12-01T18:30:18.835Z - error: uncaughtException: ___dirname is not defined
ReferenceError: ___dirname is not defined
    at Query.onResult (D:\2609 PROJECT\routes\products.js:21:24)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11) error=ReferenceError: ___dirname is not defined, stack=ReferenceError: ___dirname is not defined
    at Query.onResult (D:\2609 PROJECT\routes\products.js:21:24)
    at D:\2609 PROJECT\node_modules\mysql2\lib\commands\query.js:86:16
    at processTicksAndRejections (node:internal/process/task_queues:78:11), exception=true, date=Thu Dec 02 2021 02:30:18 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object]
2021-12-02T20:06:54.174Z - error: uncaughtException: Unknown column 'id' in 'where clause'
Error: Unknown column 'id' in 'where clause'
    at Packet.asError (D:\2609 PROJECT\node_modules\mysql2\lib\packets\packet.js:722:17)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10) error=Error: Unknown column 'id' in 'where clause', stack=Error: Unknown column 'id' in 'where clause'
    at Packet.asError (D:\2609 PROJECT\node_modules\mysql2\lib\packets\packet.js:722:17)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10), exception=true, date=Fri Dec 03 2021 04:06:54 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
2021-12-03T14:08:16.799Z - error: uncaughtException: Cannot delete or update a parent row: a foreign key constraint fails (`foodorder`.`orders`, CONSTRAINT `idfood` FOREIGN KEY (`food_id`) REFERENCES `products` (`food_id`))
Error: Cannot delete or update a parent row: a foreign key constraint fails (`foodorder`.`orders`, CONSTRAINT `idfood` FOREIGN KEY (`food_id`) REFERENCES `products` (`food_id`))
    at Packet.asError (D:\2609 PROJECT\node_modules\mysql2\lib\packets\packet.js:722:17)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10) error=Error: Cannot delete or update a parent row: a foreign key constraint fails (`foodorder`.`orders`, CONSTRAINT `idfood` FOREIGN KEY (`food_id`) REFERENCES `products` (`food_id`)), stack=Error: Cannot delete or update a parent row: a foreign key constraint fails (`foodorder`.`orders`, CONSTRAINT `idfood` FOREIGN KEY (`food_id`) REFERENCES `products` (`food_id`))
    at Packet.asError (D:\2609 PROJECT\node_modules\mysql2\lib\packets\packet.js:722:17)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10), exception=true, date=Fri Dec 03 2021 22:08:16 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
2021-12-03T19:24:38.978Z - error: uncaughtException: Unknown column 'admin_id' in 'where clause'
Error: Unknown column 'admin_id' in 'where clause'
    at Packet.asError (D:\2609 PROJECT\node_modules\mysql2\lib\packets\packet.js:722:17)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10) error=Error: Unknown column 'admin_id' in 'where clause', stack=Error: Unknown column 'admin_id' in 'where clause'
    at Packet.asError (D:\2609 PROJECT\node_modules\mysql2\lib\packets\packet.js:722:17)
    at Query.execute (D:\2609 PROJECT\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (D:\2609 PROJECT\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\2609 PROJECT\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10), exception=true, date=Sat Dec 04 2021 03:24:38 GMT+0800 (Philippine Standard Time), process=[object Object], os=[object Object], trace=[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
